# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Nov  1 09:51:01 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 852)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(9, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setMinimumSize(QtCore.QSize(0, 30))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolButton = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(0, 30))
        self.toolButton.setStyleSheet("QToolButton{\n"
"    border: none;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    text-transform: uppercase;\n"
"    background-color:rgb(0,102,255);\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(275, 30))
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"\n"
"}\n"
"QToolButton{\n"
"    border: none;\n"
"    font: 13pt \"Arial Rounded MT\";\n"
"    text-transform: uppercase;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color:rgb(102,178,255)\n"
"}\n"
"QToolButton:checked{\n"
"    background-color:rgb(102,178,255)\n"
"}\n"
"QToolButton#tbAcquire, #tbLoad, #tbAddKey, #tbAddHash, #tbIgnoreFolders, #tbSystemArtifacts{\n"
"    border: none;\n"
"    font: 10pt \"Arial Rounded MT\";\n"
"    text-transform: none;    \n"
"\n"
"    \n"
"    \n"
"}")
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolButton1 = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton1.sizePolicy().hasHeightForWidth())
        self.toolButton1.setSizePolicy(sizePolicy)
        self.toolButton1.setMinimumSize(QtCore.QSize(280, 40))
        self.toolButton1.setBaseSize(QtCore.QSize(200, 0))
        self.toolButton1.setStyleSheet("")
        self.toolButton1.setCheckable(True)
        self.toolButton1.setAutoExclusive(True)
        self.toolButton1.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton1.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton1.setObjectName("toolButton1")
        self.verticalLayout.addWidget(self.toolButton1)
        self.toolButton_2 = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMinimumSize(QtCore.QSize(280, 40))
        self.toolButton_2.setCheckable(True)
        self.toolButton_2.setAutoExclusive(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout.addWidget(self.toolButton_2)
        self.tbAcquire = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbAcquire.sizePolicy().hasHeightForWidth())
        self.tbAcquire.setSizePolicy(sizePolicy)
        self.tbAcquire.setMinimumSize(QtCore.QSize(280, 30))
        self.tbAcquire.setCheckable(True)
        self.tbAcquire.setAutoExclusive(True)
        self.tbAcquire.setObjectName("tbAcquire")
        self.verticalLayout.addWidget(self.tbAcquire)
        self.tbLoad = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbLoad.sizePolicy().hasHeightForWidth())
        self.tbLoad.setSizePolicy(sizePolicy)
        self.tbLoad.setMinimumSize(QtCore.QSize(280, 30))
        self.tbLoad.setCheckable(True)
        self.tbLoad.setAutoExclusive(True)
        self.tbLoad.setObjectName("tbLoad")
        self.verticalLayout.addWidget(self.tbLoad)
        self.tbProcessing = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbProcessing.sizePolicy().hasHeightForWidth())
        self.tbProcessing.setSizePolicy(sizePolicy)
        self.tbProcessing.setMinimumSize(QtCore.QSize(280, 40))
        self.tbProcessing.setCheckable(True)
        self.tbProcessing.setAutoExclusive(True)
        self.tbProcessing.setObjectName("tbProcessing")
        self.verticalLayout.addWidget(self.tbProcessing)
        self.tbAddKey = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbAddKey.sizePolicy().hasHeightForWidth())
        self.tbAddKey.setSizePolicy(sizePolicy)
        self.tbAddKey.setMinimumSize(QtCore.QSize(280, 30))
        self.tbAddKey.setObjectName("tbAddKey")
        self.verticalLayout.addWidget(self.tbAddKey)
        self.tbAddHash = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbAddHash.sizePolicy().hasHeightForWidth())
        self.tbAddHash.setSizePolicy(sizePolicy)
        self.tbAddHash.setMinimumSize(QtCore.QSize(275, 30))
        self.tbAddHash.setObjectName("tbAddHash")
        self.verticalLayout.addWidget(self.tbAddHash)
        self.tbIgnoreFolders = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbIgnoreFolders.sizePolicy().hasHeightForWidth())
        self.tbIgnoreFolders.setSizePolicy(sizePolicy)
        self.tbIgnoreFolders.setMinimumSize(QtCore.QSize(282, 30))
        self.tbIgnoreFolders.setObjectName("tbIgnoreFolders")
        self.verticalLayout.addWidget(self.tbIgnoreFolders)
        self.tbSystemArtifacts = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbSystemArtifacts.sizePolicy().hasHeightForWidth())
        self.tbSystemArtifacts.setSizePolicy(sizePolicy)
        self.tbSystemArtifacts.setMinimumSize(QtCore.QSize(282, 30))
        self.tbSystemArtifacts.setObjectName("tbSystemArtifacts")
        self.verticalLayout.addWidget(self.tbSystemArtifacts)
        self.toolButton_3 = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMinimumSize(QtCore.QSize(280, 40))
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout.addWidget(self.toolButton_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 1)
        self.lblCasedetails = QtGui.QLabel(self.centralwidget)
        self.lblCasedetails.setStyleSheet("QLabel{\n"
"    text-transform: uppercase;\n"
"    \n"
"    font: 75 16pt \"Arial Rounded MT Bold\";\n"
"\n"
"}")
        self.lblCasedetails.setObjectName("lblCasedetails")
        self.gridLayout.addWidget(self.lblCasedetails, 2, 1, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("QstackedWidget{\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"    text-transform: none;\n"
"\n"
"}\n"
"\n"
"QLabel#lblCaseInfo, #lblReportOptions, #lblKeywords, #lblKeywords_2, #lblLists, #lblAddKeywordsToSearch, #lblAddHashFilesToSearch, #lblIgnoreFolders, #lblOS_Artifacts{\n"
"    text-transform: uppercase;\n"
"    font: 13pt \"Arial Rounded MT Bold\";\n"
"    margin-left: 10px\n"
"}\n"
"\n"
"QLabel#lblCaseNr, #lblFolder, #lblFile, #lblDate, #lblExam, #lblDescr, #lblCover, #lblImage, #lblKey, #lblKeywordsAdded, #lblListsAdded, #lblAddKeywordsToSearch_2, #lblAddHashFilesToSearch_txt, #lblIgnoreFolders_txt, #lblOS_Artifacts_txt{\n"
"    font: 9pt \"Arial Rounded MT\";\n"
"    text-transform: none;    \n"
"    margin-left: 10px    ;\n"
"\n"
"}\n"
"\n"
"#tbBrowsePath, #tbBrowseCover{\n"
"    color: rgb(0,102,255);\n"
"    text-transform: uppercase;\n"
"    font: 10pt \"Arial Rounded MT\";\n"
"    border: none;\n"
"}\n"
"\n"
"#tbAddKeyword, #tbAddList{\n"
"\n"
"    color: rgb(0,102,255);\n"
"    text-transform: uppercase;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    border: none;\n"
"    margin-left: 10px    ;    \n"
"}\n"
"\n"
"#tbAddKeywordToSearch, #tbAddHashFilesToSearch, #tbIgnoreFolders_2, #tbOS_Artifacts{\n"
"    margin-left: 10px;\n"
"    text-transform: uppercase;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    \n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    \n"
"\n"
"\n"
"    color: rgb(0,102,255)\n"
"}\n"
"")
        self.stackedWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.casedetails = QtGui.QWidget()
        self.casedetails.setObjectName("casedetails")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.casedetails)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.casedetails)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblCover = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCover.sizePolicy().hasHeightForWidth())
        self.lblCover.setSizePolicy(sizePolicy)
        self.lblCover.setMinimumSize(QtCore.QSize(0, 30))
        self.lblCover.setObjectName("lblCover")
        self.gridLayout_4.addWidget(self.lblCover, 12, 1, 1, 1)
        self.tbBrowseCover = QtGui.QToolButton(self.casedetails)
        self.tbBrowseCover.setObjectName("tbBrowseCover")
        self.gridLayout_4.addWidget(self.tbBrowseCover, 12, 3, 1, 1)
        self.lblReportOptions = QtGui.QLabel(self.casedetails)
        self.lblReportOptions.setObjectName("lblReportOptions")
        self.gridLayout_4.addWidget(self.lblReportOptions, 11, 0, 1, 2)
        self.label_14 = QtGui.QLabel(self.casedetails)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 10, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.casedetails)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 9, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.casedetails)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 6, 1, 1, 1)
        self.lblDate = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setMinimumSize(QtCore.QSize(0, 30))
        self.lblDate.setObjectName("lblDate")
        self.gridLayout_4.addWidget(self.lblDate, 5, 1, 1, 1)
        self.lblExam = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExam.sizePolicy().hasHeightForWidth())
        self.lblExam.setSizePolicy(sizePolicy)
        self.lblExam.setMinimumSize(QtCore.QSize(0, 30))
        self.lblExam.setObjectName("lblExam")
        self.gridLayout_4.addWidget(self.lblExam, 7, 1, 1, 1)
        self.lblDescr = QtGui.QLabel(self.casedetails)
        self.lblDescr.setObjectName("lblDescr")
        self.gridLayout_4.addWidget(self.lblDescr, 8, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(225, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 3, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.lblFolder = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFolder.sizePolicy().hasHeightForWidth())
        self.lblFolder.setSizePolicy(sizePolicy)
        self.lblFolder.setMinimumSize(QtCore.QSize(0, 30))
        self.lblFolder.setObjectName("lblFolder")
        self.gridLayout_4.addWidget(self.lblFolder, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.lblCaseNr = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCaseNr.sizePolicy().hasHeightForWidth())
        self.lblCaseNr.setSizePolicy(sizePolicy)
        self.lblCaseNr.setMinimumSize(QtCore.QSize(0, 30))
        self.lblCaseNr.setObjectName("lblCaseNr")
        self.gridLayout_4.addWidget(self.lblCaseNr, 1, 1, 1, 1)
        self.lblFile = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFile.sizePolicy().hasHeightForWidth())
        self.lblFile.setSizePolicy(sizePolicy)
        self.lblFile.setMinimumSize(QtCore.QSize(0, 30))
        self.lblFile.setObjectName("lblFile")
        self.gridLayout_4.addWidget(self.lblFile, 4, 1, 1, 1)
        self.lblImage = QtGui.QLabel(self.casedetails)
        self.lblImage.setObjectName("lblImage")
        self.gridLayout_4.addWidget(self.lblImage, 13, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 5, 2, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.casedetails)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 8, 2, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 3, 2, 1, 1)
        self.lblCaseInfo = QtGui.QLabel(self.casedetails)
        self.lblCaseInfo.setObjectName("lblCaseInfo")
        self.gridLayout_4.addWidget(self.lblCaseInfo, 0, 0, 1, 2)
        self.lineEdit_3 = QtGui.QLineEdit(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 4, 2, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_4.addWidget(self.lineEdit_4, 7, 2, 1, 1)
        self.tbBrowsePath = QtGui.QToolButton(self.casedetails)
        self.tbBrowsePath.setObjectName("tbBrowsePath")
        self.gridLayout_4.addWidget(self.tbBrowsePath, 4, 3, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 12, 2, 1, 1)
        self.label = QtGui.QLabel(self.casedetails)
        self.label.setMinimumSize(QtCore.QSize(0, 80))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 14, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.stackedWidget.addWidget(self.casedetails)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblKeywords = QtGui.QLabel(self.page_2)
        self.lblKeywords.setObjectName("lblKeywords")
        self.gridLayout_2.addWidget(self.lblKeywords, 1, 0, 1, 1)
        self.lblKey = QtGui.QLabel(self.page_2)
        self.lblKey.setObjectName("lblKey")
        self.gridLayout_2.addWidget(self.lblKey, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 3, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblLists = QtGui.QLabel(self.page_2)
        self.lblLists.setObjectName("lblLists")
        self.verticalLayout_5.addWidget(self.lblLists)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbAddList = QtGui.QToolButton(self.page_2)
        self.tbAddList.setObjectName("tbAddList")
        self.horizontalLayout_2.addWidget(self.tbAddList)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.lblListsAdded = QtGui.QLabel(self.page_2)
        self.lblListsAdded.setObjectName("lblListsAdded")
        self.horizontalLayout_2.addWidget(self.lblListsAdded)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.tableView = QtGui.QTableView(self.page_2)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_4.addWidget(self.tableView)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem8)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblKeywords_2 = QtGui.QLabel(self.page_2)
        self.lblKeywords_2.setObjectName("lblKeywords_2")
        self.verticalLayout_6.addWidget(self.lblKeywords_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tbAddKeyword = QtGui.QToolButton(self.page_2)
        self.tbAddKeyword.setObjectName("tbAddKeyword")
        self.horizontalLayout_3.addWidget(self.tbAddKeyword)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.lblKeywordsAdded = QtGui.QLabel(self.page_2)
        self.lblKeywordsAdded.setObjectName("lblKeywordsAdded")
        self.horizontalLayout_3.addWidget(self.lblKeywordsAdded)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem10 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.tableView_2 = QtGui.QTableView(self.page_2)
        self.tableView_2.setObjectName("tableView_2")
        self.horizontalLayout_5.addWidget(self.tableView_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem11)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem12)
        self.lblAddKeywordsToSearch = QtGui.QLabel(self.page_3)
        self.lblAddKeywordsToSearch.setObjectName("lblAddKeywordsToSearch")
        self.verticalLayout_8.addWidget(self.lblAddKeywordsToSearch)
        self.lblAddKeywordsToSearch_2 = QtGui.QLabel(self.page_3)
        self.lblAddKeywordsToSearch_2.setObjectName("lblAddKeywordsToSearch_2")
        self.verticalLayout_8.addWidget(self.lblAddKeywordsToSearch_2)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem13)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tbAddKeywordToSearch = QtGui.QToolButton(self.page_3)
        self.tbAddKeywordToSearch.setObjectName("tbAddKeywordToSearch")
        self.horizontalLayout_7.addWidget(self.tbAddKeywordToSearch)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem15)
        self.lblAddHashFilesToSearch = QtGui.QLabel(self.page_3)
        self.lblAddHashFilesToSearch.setObjectName("lblAddHashFilesToSearch")
        self.verticalLayout_11.addWidget(self.lblAddHashFilesToSearch)
        self.lblAddHashFilesToSearch_txt = QtGui.QLabel(self.page_3)
        self.lblAddHashFilesToSearch_txt.setObjectName("lblAddHashFilesToSearch_txt")
        self.verticalLayout_11.addWidget(self.lblAddHashFilesToSearch_txt)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem16)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tbAddHashFilesToSearch = QtGui.QToolButton(self.page_3)
        self.tbAddHashFilesToSearch.setObjectName("tbAddHashFilesToSearch")
        self.horizontalLayout_8.addWidget(self.tbAddHashFilesToSearch)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem17)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem18)
        self.lblIgnoreFolders = QtGui.QLabel(self.page_3)
        self.lblIgnoreFolders.setObjectName("lblIgnoreFolders")
        self.verticalLayout_9.addWidget(self.lblIgnoreFolders)
        self.lblIgnoreFolders_txt = QtGui.QLabel(self.page_3)
        self.lblIgnoreFolders_txt.setObjectName("lblIgnoreFolders_txt")
        self.verticalLayout_9.addWidget(self.lblIgnoreFolders_txt)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem19)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tbIgnoreFolders_2 = QtGui.QToolButton(self.page_3)
        self.tbIgnoreFolders_2.setObjectName("tbIgnoreFolders_2")
        self.horizontalLayout_9.addWidget(self.tbIgnoreFolders_2)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem20)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem21)
        self.lblOS_Artifacts = QtGui.QLabel(self.page_3)
        self.lblOS_Artifacts.setObjectName("lblOS_Artifacts")
        self.verticalLayout_10.addWidget(self.lblOS_Artifacts)
        self.lblOS_Artifacts_txt = QtGui.QLabel(self.page_3)
        self.lblOS_Artifacts_txt.setObjectName("lblOS_Artifacts_txt")
        self.verticalLayout_10.addWidget(self.lblOS_Artifacts_txt)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem22)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tbOS_Artifacts = QtGui.QToolButton(self.page_3)
        self.tbOS_Artifacts.setObjectName("tbOS_Artifacts")
        self.horizontalLayout_10.addWidget(self.tbOS_Artifacts)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem23)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem24)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_DigiBaseReclass_Examine = QtGui.QAction(MainWindow)
        self.actionOpen_DigiBaseReclass_Examine.setObjectName("actionOpen_DigiBaseReclass_Examine")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen_DigiBaseReclass_Examine)
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DigiBaseReclass Process", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "        Go to evidence       ", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton1.setText(QtGui.QApplication.translate("MainWindow", "Case Details                  ", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "Evidence sources         ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAcquire.setText(QtGui.QApplication.translate("MainWindow", "   Acquire evidence", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLoad.setText(QtGui.QApplication.translate("MainWindow", "Load evidence", None, QtGui.QApplication.UnicodeUTF8))
        self.tbProcessing.setText(QtGui.QApplication.translate("MainWindow", "Processing details      ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddKey.setText(QtGui.QApplication.translate("MainWindow", "            Add keywords to search", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddHash.setText(QtGui.QApplication.translate("MainWindow", "            Add Hash files to search", None, QtGui.QApplication.UnicodeUTF8))
        self.tbIgnoreFolders.setText(QtGui.QApplication.translate("MainWindow", "  Ignore Folder(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSystemArtifacts.setText(QtGui.QApplication.translate("MainWindow", "         Add  System artifacts", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("MainWindow", "analyze evidence           ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCasedetails.setText(QtGui.QApplication.translate("MainWindow", "case details", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCover.setText(QtGui.QApplication.translate("MainWindow", "Cover logo", None, QtGui.QApplication.UnicodeUTF8))
        self.tbBrowseCover.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReportOptions.setText(QtGui.QApplication.translate("MainWindow", "Report options", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDate.setText(QtGui.QApplication.translate("MainWindow", "Date created", None, QtGui.QApplication.UnicodeUTF8))
        self.lblExam.setText(QtGui.QApplication.translate("MainWindow", "Examiner", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescr.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFolder.setText(QtGui.QApplication.translate("MainWindow", "Folder name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCaseNr.setText(QtGui.QApplication.translate("MainWindow", "Case number", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFile.setText(QtGui.QApplication.translate("MainWindow", "File path", None, QtGui.QApplication.UnicodeUTF8))
        self.lblImage.setText(QtGui.QApplication.translate("MainWindow", "Image resized to 150 x 150 pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCaseInfo.setText(QtGui.QApplication.translate("MainWindow", "Case Information", None, QtGui.QApplication.UnicodeUTF8))
        self.tbBrowsePath.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKeywords.setText(QtGui.QApplication.translate("MainWindow", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKey.setText(QtGui.QApplication.translate("MainWindow", "Keywords that include in your search are specified in number of hits in the results. \n"
"You can import a list of keywords or enter them manualy in the Keywords table below.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLists.setText(QtGui.QApplication.translate("MainWindow", "Lists", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddList.setText(QtGui.QApplication.translate("MainWindow", "add lists", None, QtGui.QApplication.UnicodeUTF8))
        self.lblListsAdded.setText(QtGui.QApplication.translate("MainWindow", "Lists added: 0", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKeywords_2.setText(QtGui.QApplication.translate("MainWindow", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddKeyword.setText(QtGui.QApplication.translate("MainWindow", "add keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKeywordsAdded.setText(QtGui.QApplication.translate("MainWindow", "Keywords added: 0", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddKeywordsToSearch.setText(QtGui.QApplication.translate("MainWindow", "Add keywords to search", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddKeywordsToSearch_2.setText(QtGui.QApplication.translate("MainWindow", "Provide the keywords that you want to include in your search. If a keyword gets a hit during the search,\n"
"it\'s added by number of hits to the results", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddKeywordToSearch.setText(QtGui.QApplication.translate("MainWindow", "add keywords to search", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddHashFilesToSearch.setText(QtGui.QApplication.translate("MainWindow", "Add Hash files to search", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddHashFilesToSearch_txt.setText(QtGui.QApplication.translate("MainWindow", "Import hashes for known media files and Project VIC files so that DigiBaseReclass catagorizes them \n"
"automatically", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddHashFilesToSearch.setText(QtGui.QApplication.translate("MainWindow", "Add Hash files to search", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIgnoreFolders.setText(QtGui.QApplication.translate("MainWindow", "Ignore folder(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIgnoreFolders_txt.setText(QtGui.QApplication.translate("MainWindow", "Provide folder(s) to exclude in the search", None, QtGui.QApplication.UnicodeUTF8))
        self.tbIgnoreFolders_2.setText(QtGui.QApplication.translate("MainWindow", "ignore folder(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOS_Artifacts.setText(QtGui.QApplication.translate("MainWindow", "Add more artifacts", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOS_Artifacts_txt.setText(QtGui.QApplication.translate("MainWindow", "Provide Operating System Artifacts ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbOS_Artifacts.setText(QtGui.QApplication.translate("MainWindow", "add operating system artifacts", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_DigiBaseReclass_Examine.setText(QtGui.QApplication.translate("MainWindow", "Open DigiBaseReclass Examine", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("MainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

