# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Nov 10 21:13:22 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 852)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(9, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setMinimumSize(QtCore.QSize(0, 30))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.tbGoTo = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbGoTo.sizePolicy().hasHeightForWidth())
        self.tbGoTo.setSizePolicy(sizePolicy)
        self.tbGoTo.setMinimumSize(QtCore.QSize(0, 30))
        self.tbGoTo.setStyleSheet("QToolButton{\n"
"    border: none;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    text-transform: uppercase;\n"
"    background-color:rgb(0,102,255);\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.tbGoTo.setObjectName("tbGoTo")
        self.horizontalLayout.addWidget(self.tbGoTo)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(275, 30))
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"\n"
"}\n"
"QToolButton{\n"
"    border: none;\n"
"    font: 13pt \"Arial Rounded MT\";\n"
"    text-transform: uppercase;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color:rgb(102,178,255)\n"
"}\n"
"QToolButton:checked{\n"
"    background-color:rgb(102,178,255)\n"
"}\n"
"QToolButton#tbAcquire, #tbLoad, #tbAddKey, #tbAddHash, #tbIgnoreFolders, #tbSystemArtifacts{\n"
"    border: none;\n"
"    font: 10pt \"Arial Rounded MT\";\n"
"    text-transform: none;    \n"
"\n"
"    \n"
"    \n"
"}")
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbCaseDetails = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCaseDetails.sizePolicy().hasHeightForWidth())
        self.tbCaseDetails.setSizePolicy(sizePolicy)
        self.tbCaseDetails.setMinimumSize(QtCore.QSize(280, 40))
        self.tbCaseDetails.setBaseSize(QtCore.QSize(200, 0))
        self.tbCaseDetails.setStyleSheet("")
        self.tbCaseDetails.setCheckable(True)
        self.tbCaseDetails.setAutoExclusive(True)
        self.tbCaseDetails.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.tbCaseDetails.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbCaseDetails.setObjectName("tbCaseDetails")
        self.verticalLayout.addWidget(self.tbCaseDetails)
        self.tbEvidenceSources = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbEvidenceSources.sizePolicy().hasHeightForWidth())
        self.tbEvidenceSources.setSizePolicy(sizePolicy)
        self.tbEvidenceSources.setMinimumSize(QtCore.QSize(280, 40))
        self.tbEvidenceSources.setCheckable(True)
        self.tbEvidenceSources.setAutoExclusive(True)
        self.tbEvidenceSources.setObjectName("tbEvidenceSources")
        self.verticalLayout.addWidget(self.tbEvidenceSources)
        self.tbAcquire = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbAcquire.sizePolicy().hasHeightForWidth())
        self.tbAcquire.setSizePolicy(sizePolicy)
        self.tbAcquire.setMinimumSize(QtCore.QSize(280, 30))
        self.tbAcquire.setCheckable(True)
        self.tbAcquire.setAutoRepeat(False)
        self.tbAcquire.setAutoExclusive(True)
        self.tbAcquire.setObjectName("tbAcquire")
        self.verticalLayout.addWidget(self.tbAcquire)
        self.tbLoad = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbLoad.sizePolicy().hasHeightForWidth())
        self.tbLoad.setSizePolicy(sizePolicy)
        self.tbLoad.setMinimumSize(QtCore.QSize(280, 30))
        self.tbLoad.setCheckable(True)
        self.tbLoad.setAutoRepeat(False)
        self.tbLoad.setAutoExclusive(True)
        self.tbLoad.setObjectName("tbLoad")
        self.verticalLayout.addWidget(self.tbLoad)
        self.tbProcessing = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbProcessing.sizePolicy().hasHeightForWidth())
        self.tbProcessing.setSizePolicy(sizePolicy)
        self.tbProcessing.setMinimumSize(QtCore.QSize(280, 40))
        self.tbProcessing.setCheckable(True)
        self.tbProcessing.setAutoExclusive(True)
        self.tbProcessing.setObjectName("tbProcessing")
        self.verticalLayout.addWidget(self.tbProcessing)
        self.tbAddKey = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbAddKey.sizePolicy().hasHeightForWidth())
        self.tbAddKey.setSizePolicy(sizePolicy)
        self.tbAddKey.setMinimumSize(QtCore.QSize(280, 30))
        self.tbAddKey.setCheckable(True)
        self.tbAddKey.setAutoRepeat(False)
        self.tbAddKey.setAutoExclusive(True)
        self.tbAddKey.setObjectName("tbAddKey")
        self.verticalLayout.addWidget(self.tbAddKey)
        self.tbAddHash = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbAddHash.sizePolicy().hasHeightForWidth())
        self.tbAddHash.setSizePolicy(sizePolicy)
        self.tbAddHash.setMinimumSize(QtCore.QSize(275, 30))
        self.tbAddHash.setCheckable(True)
        self.tbAddHash.setAutoRepeat(False)
        self.tbAddHash.setAutoExclusive(True)
        self.tbAddHash.setObjectName("tbAddHash")
        self.verticalLayout.addWidget(self.tbAddHash)
        self.tbIgnoreFolders = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbIgnoreFolders.sizePolicy().hasHeightForWidth())
        self.tbIgnoreFolders.setSizePolicy(sizePolicy)
        self.tbIgnoreFolders.setMinimumSize(QtCore.QSize(282, 30))
        self.tbIgnoreFolders.setCheckable(True)
        self.tbIgnoreFolders.setAutoRepeat(False)
        self.tbIgnoreFolders.setAutoExclusive(True)
        self.tbIgnoreFolders.setObjectName("tbIgnoreFolders")
        self.verticalLayout.addWidget(self.tbIgnoreFolders)
        self.tbSystemArtifacts = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbSystemArtifacts.sizePolicy().hasHeightForWidth())
        self.tbSystemArtifacts.setSizePolicy(sizePolicy)
        self.tbSystemArtifacts.setMinimumSize(QtCore.QSize(282, 30))
        self.tbSystemArtifacts.setCheckable(True)
        self.tbSystemArtifacts.setAutoRepeat(False)
        self.tbSystemArtifacts.setAutoExclusive(True)
        self.tbSystemArtifacts.setObjectName("tbSystemArtifacts")
        self.verticalLayout.addWidget(self.tbSystemArtifacts)
        self.toolButton_3 = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMinimumSize(QtCore.QSize(280, 40))
        self.toolButton_3.setCheckable(True)
        self.toolButton_3.setAutoExclusive(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout.addWidget(self.toolButton_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 1)
        self.lblCasedetails = QtGui.QLabel(self.centralwidget)
        self.lblCasedetails.setStyleSheet("QLabel{\n"
"    text-transform: uppercase;\n"
"    \n"
"    font: 75 16pt \"Arial Rounded MT Bold\";\n"
"\n"
"}")
        self.lblCasedetails.setText("")
        self.lblCasedetails.setObjectName("lblCasedetails")
        self.gridLayout.addWidget(self.lblCasedetails, 2, 1, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setStyleSheet("QstackedWidget{\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"    text-transform: none;\n"
"\n"
"}\n"
"\n"
"QLabel#lblCaseInfo, #lblReportOptions, #lblKeywords, #lblKeywords_2, #lblLists, #lblAddKeywordsToSearch, #lblAddHashFilesToSearch, #lblIgnoreFolders, #lblOS_Artifacts, #lblLoadHashFiles, #lblLoadProjectVic, #lblIgnoreFolders_2, #lblSourcesToProcess, #lblLoadEvidence{\n"
"    text-transform: uppercase;\n"
"    font: 13pt \"Arial Rounded MT Bold\";\n"
"    margin-left: 10px\n"
"}\n"
"\n"
"QLabel#lblCaseNr, #lblFolder, #lblFile, #lblDate, #lblExam, #lblDescr, #lblCover, #lblImage, #lblKey, #lblKeywordsAdded, #lblListsAdded, #lblAddKeywordsToSearch_2, #lblAddHashFilesToSearch_txt, #lblIgnoreFolders_txt, #lblOS_Artifacts_tx,  #lblLoadHashFiles_txt, #lblLoadProjectVic_txt, #lblLoadProjectVic_photodna_txt, #lblLoadHashFiles_rec_loaded, #lblLoadProjectVic_rec_loaded,\n"
"#lblIgnoreFolders_txt_2, #lblIgnoreFolders_Records{\n"
"    font: 9pt \"Arial Rounded MT\";\n"
"    text-transform: none;    \n"
"    margin-left: 10px    ;\n"
"\n"
"}\n"
"\n"
"#tbBrowsePath, #tbBrowseCover{\n"
"    color: rgb(0,102,255);\n"
"    text-transform: uppercase;\n"
"    font: 10pt \"Arial Rounded MT\";\n"
"    border: none;\n"
"}\n"
"\n"
"#tbAddKeyword, #tbAddList, #tbLoadHashFiles, #tbLoadProjectVic, #tbLoadProjectVic_edit, #tbIgnoreFoldersDel,\n"
"#tbIgnoreFoldersAdd{\n"
"\n"
"    color: rgb(0,102,255);\n"
"    text-transform: uppercase;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    border: none;\n"
"    margin-left: 10px    ;    \n"
"}\n"
"\n"
"#tbAddKeywordToSearch, #tbAddHashFilesToSearch, #tbIgnoreFolders_2, #tbOS_Artifacts, #tbAcquireEvidence, #tbLoadEvidence{\n"
"    \n"
"margin-left: 10px;\n"
"    text-transform: uppercase;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    color: rgb(0,102,255)\n"
"}\n"
"\n"
"#tbDrives, #tbMobile, #tbAndroid, #tbFilesFolders{    \n"
"    image: url(\":/icons/open.png\");   \n"
"    font: 13pt \"Arial Rounded MT\";\n"
"    border-radius:10px;\n"
"    background-color: #808080;\n"
"    color: white;\n"
"    border: 4px solid black; \n"
"\n"
"}\n"
"")
        self.stackedWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.casedetails = QtGui.QWidget()
        self.casedetails.setObjectName("casedetails")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.casedetails)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.casedetails)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblCover = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCover.sizePolicy().hasHeightForWidth())
        self.lblCover.setSizePolicy(sizePolicy)
        self.lblCover.setMinimumSize(QtCore.QSize(0, 30))
        self.lblCover.setObjectName("lblCover")
        self.gridLayout_4.addWidget(self.lblCover, 12, 1, 1, 1)
        self.tbBrowseCover = QtGui.QToolButton(self.casedetails)
        self.tbBrowseCover.setObjectName("tbBrowseCover")
        self.gridLayout_4.addWidget(self.tbBrowseCover, 12, 3, 1, 1)
        self.lblReportOptions = QtGui.QLabel(self.casedetails)
        self.lblReportOptions.setObjectName("lblReportOptions")
        self.gridLayout_4.addWidget(self.lblReportOptions, 11, 0, 1, 2)
        self.label_14 = QtGui.QLabel(self.casedetails)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 10, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.casedetails)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 9, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.casedetails)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 6, 1, 1, 1)
        self.lblDate = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setMinimumSize(QtCore.QSize(0, 30))
        self.lblDate.setObjectName("lblDate")
        self.gridLayout_4.addWidget(self.lblDate, 5, 1, 1, 1)
        self.lblExam = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExam.sizePolicy().hasHeightForWidth())
        self.lblExam.setSizePolicy(sizePolicy)
        self.lblExam.setMinimumSize(QtCore.QSize(0, 30))
        self.lblExam.setObjectName("lblExam")
        self.gridLayout_4.addWidget(self.lblExam, 7, 1, 1, 1)
        self.lblDescr = QtGui.QLabel(self.casedetails)
        self.lblDescr.setObjectName("lblDescr")
        self.gridLayout_4.addWidget(self.lblDescr, 8, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(225, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 3, 1, 1)
        self.leCaseNumber = QtGui.QLineEdit(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCaseNumber.sizePolicy().hasHeightForWidth())
        self.leCaseNumber.setSizePolicy(sizePolicy)
        self.leCaseNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.leCaseNumber.setObjectName("leCaseNumber")
        self.gridLayout_4.addWidget(self.leCaseNumber, 1, 2, 1, 1)
        self.lblFolder = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFolder.sizePolicy().hasHeightForWidth())
        self.lblFolder.setSizePolicy(sizePolicy)
        self.lblFolder.setMinimumSize(QtCore.QSize(0, 30))
        self.lblFolder.setObjectName("lblFolder")
        self.gridLayout_4.addWidget(self.lblFolder, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.lblCaseNr = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCaseNr.sizePolicy().hasHeightForWidth())
        self.lblCaseNr.setSizePolicy(sizePolicy)
        self.lblCaseNr.setMinimumSize(QtCore.QSize(0, 30))
        self.lblCaseNr.setObjectName("lblCaseNr")
        self.gridLayout_4.addWidget(self.lblCaseNr, 1, 1, 1, 1)
        self.lblFile = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFile.sizePolicy().hasHeightForWidth())
        self.lblFile.setSizePolicy(sizePolicy)
        self.lblFile.setMinimumSize(QtCore.QSize(0, 30))
        self.lblFile.setObjectName("lblFile")
        self.gridLayout_4.addWidget(self.lblFile, 4, 1, 1, 1)
        self.lblImage = QtGui.QLabel(self.casedetails)
        self.lblImage.setObjectName("lblImage")
        self.gridLayout_4.addWidget(self.lblImage, 13, 2, 1, 1)
        self.lblDateCreated = QtGui.QLabel(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateCreated.sizePolicy().hasHeightForWidth())
        self.lblDateCreated.setSizePolicy(sizePolicy)
        self.lblDateCreated.setMinimumSize(QtCore.QSize(0, 30))
        self.lblDateCreated.setText("")
        self.lblDateCreated.setObjectName("lblDateCreated")
        self.gridLayout_4.addWidget(self.lblDateCreated, 5, 2, 1, 1)
        self.leCaseName = QtGui.QLineEdit(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCaseName.sizePolicy().hasHeightForWidth())
        self.leCaseName.setSizePolicy(sizePolicy)
        self.leCaseName.setMinimumSize(QtCore.QSize(0, 30))
        self.leCaseName.setObjectName("leCaseName")
        self.gridLayout_4.addWidget(self.leCaseName, 3, 2, 1, 1)
        self.lblCaseInfo = QtGui.QLabel(self.casedetails)
        self.lblCaseInfo.setObjectName("lblCaseInfo")
        self.gridLayout_4.addWidget(self.lblCaseInfo, 0, 0, 1, 2)
        self.leFilePath = QtGui.QLineEdit(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leFilePath.sizePolicy().hasHeightForWidth())
        self.leFilePath.setSizePolicy(sizePolicy)
        self.leFilePath.setMinimumSize(QtCore.QSize(0, 30))
        self.leFilePath.setObjectName("leFilePath")
        self.gridLayout_4.addWidget(self.leFilePath, 4, 2, 1, 1)
        self.leExaminer = QtGui.QLineEdit(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExaminer.sizePolicy().hasHeightForWidth())
        self.leExaminer.setSizePolicy(sizePolicy)
        self.leExaminer.setMinimumSize(QtCore.QSize(0, 30))
        self.leExaminer.setObjectName("leExaminer")
        self.gridLayout_4.addWidget(self.leExaminer, 7, 2, 1, 1)
        self.tbBrowsePath = QtGui.QToolButton(self.casedetails)
        self.tbBrowsePath.setObjectName("tbBrowsePath")
        self.gridLayout_4.addWidget(self.tbBrowsePath, 4, 3, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.casedetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 12, 2, 1, 1)
        self.label = QtGui.QLabel(self.casedetails)
        self.label.setMinimumSize(QtCore.QSize(0, 80))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 14, 2, 1, 1)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.casedetails)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 8, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.stackedWidget.addWidget(self.casedetails)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_5 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout_3.addLayout(self.verticalLayout_22, 0, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem4 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.tbDrives = QtGui.QToolButton(self.page_6)
        self.tbDrives.setMinimumSize(QtCore.QSize(160, 160))
        self.tbDrives.setCheckable(True)
        self.tbDrives.setAutoExclusive(True)
        self.tbDrives.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbDrives.setObjectName("tbDrives")
        self.horizontalLayout_19.addWidget(self.tbDrives)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.tbFilesFolders = QtGui.QToolButton(self.page_6)
        self.tbFilesFolders.setMinimumSize(QtCore.QSize(160, 160))
        self.tbFilesFolders.setObjectName("tbFilesFolders")
        self.horizontalLayout_19.addWidget(self.tbFilesFolders)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.tbMobile = QtGui.QToolButton(self.page_6)
        self.tbMobile.setMinimumSize(QtCore.QSize(160, 160))
        self.tbMobile.setObjectName("tbMobile")
        self.horizontalLayout_19.addWidget(self.tbMobile)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem7)
        self.tbAndroid = QtGui.QToolButton(self.page_6)
        self.tbAndroid.setMinimumSize(QtCore.QSize(160, 160))
        self.tbAndroid.setObjectName("tbAndroid")
        self.horizontalLayout_19.addWidget(self.tbAndroid)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.gridLayout_3.addLayout(self.horizontalLayout_19, 4, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 5, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem10, 3, 0, 1, 1)
        self.lblLoadEvidence = QtGui.QLabel(self.page_6)
        self.lblLoadEvidence.setObjectName("lblLoadEvidence")
        self.gridLayout_3.addWidget(self.lblLoadEvidence, 2, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem11, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblKeywords = QtGui.QLabel(self.page_2)
        self.lblKeywords.setObjectName("lblKeywords")
        self.gridLayout_2.addWidget(self.lblKeywords, 1, 0, 1, 1)
        self.lblKey = QtGui.QLabel(self.page_2)
        self.lblKey.setObjectName("lblKey")
        self.gridLayout_2.addWidget(self.lblKey, 2, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 3, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblLists = QtGui.QLabel(self.page_2)
        self.lblLists.setObjectName("lblLists")
        self.verticalLayout_5.addWidget(self.lblLists)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbAddList = QtGui.QToolButton(self.page_2)
        self.tbAddList.setObjectName("tbAddList")
        self.horizontalLayout_2.addWidget(self.tbAddList)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.lblListsAdded = QtGui.QLabel(self.page_2)
        self.lblListsAdded.setObjectName("lblListsAdded")
        self.horizontalLayout_2.addWidget(self.lblListsAdded)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem15 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.tableView = QtGui.QTableView(self.page_2)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_4.addWidget(self.tableView)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem16)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblKeywords_2 = QtGui.QLabel(self.page_2)
        self.lblKeywords_2.setObjectName("lblKeywords_2")
        self.verticalLayout_6.addWidget(self.lblKeywords_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tbAddKeyword = QtGui.QToolButton(self.page_2)
        self.tbAddKeyword.setObjectName("tbAddKeyword")
        self.horizontalLayout_3.addWidget(self.tbAddKeyword)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.lblKeywordsAdded = QtGui.QLabel(self.page_2)
        self.lblKeywordsAdded.setObjectName("lblKeywordsAdded")
        self.horizontalLayout_3.addWidget(self.lblKeywordsAdded)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem18 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.tableView_2 = QtGui.QTableView(self.page_2)
        self.tableView_2.setObjectName("tableView_2")
        self.horizontalLayout_5.addWidget(self.tableView_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem19)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem20)
        self.lblAddKeywordsToSearch = QtGui.QLabel(self.page_3)
        self.lblAddKeywordsToSearch.setObjectName("lblAddKeywordsToSearch")
        self.verticalLayout_8.addWidget(self.lblAddKeywordsToSearch)
        self.lblAddKeywordsToSearch_2 = QtGui.QLabel(self.page_3)
        self.lblAddKeywordsToSearch_2.setObjectName("lblAddKeywordsToSearch_2")
        self.verticalLayout_8.addWidget(self.lblAddKeywordsToSearch_2)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem21)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tbAddKeywordToSearch = QtGui.QToolButton(self.page_3)
        self.tbAddKeywordToSearch.setCheckable(True)
        self.tbAddKeywordToSearch.setAutoExclusive(True)
        self.tbAddKeywordToSearch.setObjectName("tbAddKeywordToSearch")
        self.horizontalLayout_7.addWidget(self.tbAddKeywordToSearch)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem22)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem23)
        self.lblAddHashFilesToSearch = QtGui.QLabel(self.page_3)
        self.lblAddHashFilesToSearch.setObjectName("lblAddHashFilesToSearch")
        self.verticalLayout_11.addWidget(self.lblAddHashFilesToSearch)
        self.lblAddHashFilesToSearch_txt = QtGui.QLabel(self.page_3)
        self.lblAddHashFilesToSearch_txt.setObjectName("lblAddHashFilesToSearch_txt")
        self.verticalLayout_11.addWidget(self.lblAddHashFilesToSearch_txt)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem24)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tbAddHashFilesToSearch = QtGui.QToolButton(self.page_3)
        self.tbAddHashFilesToSearch.setCheckable(True)
        self.tbAddHashFilesToSearch.setAutoExclusive(True)
        self.tbAddHashFilesToSearch.setObjectName("tbAddHashFilesToSearch")
        self.horizontalLayout_8.addWidget(self.tbAddHashFilesToSearch)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem25)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem26)
        self.lblIgnoreFolders = QtGui.QLabel(self.page_3)
        self.lblIgnoreFolders.setObjectName("lblIgnoreFolders")
        self.verticalLayout_9.addWidget(self.lblIgnoreFolders)
        self.lblIgnoreFolders_txt = QtGui.QLabel(self.page_3)
        self.lblIgnoreFolders_txt.setObjectName("lblIgnoreFolders_txt")
        self.verticalLayout_9.addWidget(self.lblIgnoreFolders_txt)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem27)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tbIgnoreFolders_2 = QtGui.QToolButton(self.page_3)
        self.tbIgnoreFolders_2.setCheckable(True)
        self.tbIgnoreFolders_2.setAutoExclusive(True)
        self.tbIgnoreFolders_2.setObjectName("tbIgnoreFolders_2")
        self.horizontalLayout_9.addWidget(self.tbIgnoreFolders_2)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem28)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem29)
        self.lblOS_Artifacts = QtGui.QLabel(self.page_3)
        self.lblOS_Artifacts.setObjectName("lblOS_Artifacts")
        self.verticalLayout_10.addWidget(self.lblOS_Artifacts)
        self.lblOS_Artifacts_txt = QtGui.QLabel(self.page_3)
        self.lblOS_Artifacts_txt.setObjectName("lblOS_Artifacts_txt")
        self.verticalLayout_10.addWidget(self.lblOS_Artifacts_txt)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem30)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tbOS_Artifacts = QtGui.QToolButton(self.page_3)
        self.tbOS_Artifacts.setCheckable(True)
        self.tbOS_Artifacts.setAutoExclusive(True)
        self.tbOS_Artifacts.setObjectName("tbOS_Artifacts")
        self.horizontalLayout_10.addWidget(self.tbOS_Artifacts)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem31)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem32)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_15.addItem(spacerItem33)
        self.lblLoadHashFiles = QtGui.QLabel(self.page_4)
        self.lblLoadHashFiles.setObjectName("lblLoadHashFiles")
        self.verticalLayout_15.addWidget(self.lblLoadHashFiles)
        self.lblLoadHashFiles_txt = QtGui.QLabel(self.page_4)
        self.lblLoadHashFiles_txt.setObjectName("lblLoadHashFiles_txt")
        self.verticalLayout_15.addWidget(self.lblLoadHashFiles_txt)
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_15.addItem(spacerItem34)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tbLoadHashFiles = QtGui.QToolButton(self.page_4)
        self.tbLoadHashFiles.setObjectName("tbLoadHashFiles")
        self.horizontalLayout_6.addWidget(self.tbLoadHashFiles)
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem35)
        self.lblLoadHashFiles_rec_loaded = QtGui.QLabel(self.page_4)
        self.lblLoadHashFiles_rec_loaded.setObjectName("lblLoadHashFiles_rec_loaded")
        self.horizontalLayout_6.addWidget(self.lblLoadHashFiles_rec_loaded)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem36 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem36)
        self.tableView_3 = QtGui.QTableView(self.page_4)
        self.tableView_3.setObjectName("tableView_3")
        self.horizontalLayout_13.addWidget(self.tableView_3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem37 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_16.addItem(spacerItem37)
        self.lblLoadProjectVic = QtGui.QLabel(self.page_4)
        self.lblLoadProjectVic.setObjectName("lblLoadProjectVic")
        self.verticalLayout_16.addWidget(self.lblLoadProjectVic)
        self.lblLoadProjectVic_txt = QtGui.QLabel(self.page_4)
        self.lblLoadProjectVic_txt.setObjectName("lblLoadProjectVic_txt")
        self.verticalLayout_16.addWidget(self.lblLoadProjectVic_txt)
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_16.addItem(spacerItem38)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lblLoadProjectVic_photodna_txt = QtGui.QLabel(self.page_4)
        self.lblLoadProjectVic_photodna_txt.setObjectName("lblLoadProjectVic_photodna_txt")
        self.horizontalLayout_12.addWidget(self.lblLoadProjectVic_photodna_txt)
        self.tbLoadProjectVic_edit = QtGui.QToolButton(self.page_4)
        self.tbLoadProjectVic_edit.setObjectName("tbLoadProjectVic_edit")
        self.horizontalLayout_12.addWidget(self.tbLoadProjectVic_edit)
        spacerItem39 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem39)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        spacerItem40 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_16.addItem(spacerItem40)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tbLoadProjectVic = QtGui.QToolButton(self.page_4)
        self.tbLoadProjectVic.setObjectName("tbLoadProjectVic")
        self.horizontalLayout_11.addWidget(self.tbLoadProjectVic)
        spacerItem41 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem41)
        self.lblLoadProjectVic_rec_loaded = QtGui.QLabel(self.page_4)
        self.lblLoadProjectVic_rec_loaded.setObjectName("lblLoadProjectVic_rec_loaded")
        self.horizontalLayout_11.addWidget(self.lblLoadProjectVic_rec_loaded)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem42 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem42)
        self.tableView_4 = QtGui.QTableView(self.page_4)
        self.tableView_4.setObjectName("tableView_4")
        self.horizontalLayout_14.addWidget(self.tableView_4)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        spacerItem43 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_17.addItem(spacerItem43)
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem44 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_18.addItem(spacerItem44)
        self.lblIgnoreFolders_2 = QtGui.QLabel(self.page)
        self.lblIgnoreFolders_2.setObjectName("lblIgnoreFolders_2")
        self.verticalLayout_18.addWidget(self.lblIgnoreFolders_2)
        self.lblIgnoreFolders_txt_2 = QtGui.QLabel(self.page)
        self.lblIgnoreFolders_txt_2.setObjectName("lblIgnoreFolders_txt_2")
        self.verticalLayout_18.addWidget(self.lblIgnoreFolders_txt_2)
        spacerItem45 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_18.addItem(spacerItem45)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.tbIgnoreFoldersAdd = QtGui.QToolButton(self.page)
        self.tbIgnoreFoldersAdd.setObjectName("tbIgnoreFoldersAdd")
        self.horizontalLayout_15.addWidget(self.tbIgnoreFoldersAdd)
        self.tbIgnoreFoldersDel = QtGui.QToolButton(self.page)
        self.tbIgnoreFoldersDel.setObjectName("tbIgnoreFoldersDel")
        self.horizontalLayout_15.addWidget(self.tbIgnoreFoldersDel)
        spacerItem46 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem46)
        self.lblIgnoreFolders_Records = QtGui.QLabel(self.page)
        self.lblIgnoreFolders_Records.setObjectName("lblIgnoreFolders_Records")
        self.horizontalLayout_15.addWidget(self.lblIgnoreFolders_Records)
        self.verticalLayout_18.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem47 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem47)
        self.textEdit_2 = QtGui.QTextEdit(self.page)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_16.addWidget(self.textEdit_2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_16)
        spacerItem48 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem48)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.stackedWidget.addWidget(self.page)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        spacerItem49 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_20.addItem(spacerItem49)
        self.lblSourcesToProcess = QtGui.QLabel(self.page_5)
        self.lblSourcesToProcess.setObjectName("lblSourcesToProcess")
        self.verticalLayout_20.addWidget(self.lblSourcesToProcess)
        spacerItem50 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_20.addItem(spacerItem50)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem51 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem51)
        self.tableView_5 = QtGui.QTableView(self.page_5)
        self.tableView_5.setObjectName("tableView_5")
        self.horizontalLayout_18.addWidget(self.tableView_5)
        self.verticalLayout_20.addLayout(self.horizontalLayout_18)
        spacerItem52 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_20.addItem(spacerItem52)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.tbAcquireEvidence = QtGui.QToolButton(self.page_5)
        self.tbAcquireEvidence.setObjectName("tbAcquireEvidence")
        self.horizontalLayout_17.addWidget(self.tbAcquireEvidence)
        self.tbLoadEvidence = QtGui.QToolButton(self.page_5)
        self.tbLoadEvidence.setObjectName("tbLoadEvidence")
        self.horizontalLayout_17.addWidget(self.tbLoadEvidence)
        spacerItem53 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem53)
        self.verticalLayout_20.addLayout(self.horizontalLayout_17)
        spacerItem54 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_20.addItem(spacerItem54)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.stackedWidget.addWidget(self.page_5)
        self.gridLayout.addWidget(self.stackedWidget, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_DigiBaseReclass_Examine = QtGui.QAction(MainWindow)
        self.actionOpen_DigiBaseReclass_Examine.setObjectName("actionOpen_DigiBaseReclass_Examine")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen_DigiBaseReclass_Examine)
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DigiBaseReclass Process", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGoTo.setText(QtGui.QApplication.translate("MainWindow", "        Go to evidence       ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCaseDetails.setText(QtGui.QApplication.translate("MainWindow", "Case Details                  ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEvidenceSources.setText(QtGui.QApplication.translate("MainWindow", "Evidence sources         ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAcquire.setText(QtGui.QApplication.translate("MainWindow", "   Acquire evidence", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLoad.setText(QtGui.QApplication.translate("MainWindow", "Load evidence", None, QtGui.QApplication.UnicodeUTF8))
        self.tbProcessing.setText(QtGui.QApplication.translate("MainWindow", "Processing details      ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddKey.setText(QtGui.QApplication.translate("MainWindow", "            Add keywords to search", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddHash.setText(QtGui.QApplication.translate("MainWindow", "            Add Hash files to search", None, QtGui.QApplication.UnicodeUTF8))
        self.tbIgnoreFolders.setText(QtGui.QApplication.translate("MainWindow", "  Ignore Folder(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSystemArtifacts.setText(QtGui.QApplication.translate("MainWindow", "         Add  System artifacts", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("MainWindow", "analyze evidence           ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCover.setText(QtGui.QApplication.translate("MainWindow", "Cover logo", None, QtGui.QApplication.UnicodeUTF8))
        self.tbBrowseCover.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReportOptions.setText(QtGui.QApplication.translate("MainWindow", "Report options", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDate.setText(QtGui.QApplication.translate("MainWindow", "Date created", None, QtGui.QApplication.UnicodeUTF8))
        self.lblExam.setText(QtGui.QApplication.translate("MainWindow", "Examiner", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescr.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFolder.setText(QtGui.QApplication.translate("MainWindow", "Case name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCaseNr.setText(QtGui.QApplication.translate("MainWindow", "Case number", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFile.setText(QtGui.QApplication.translate("MainWindow", "File path", None, QtGui.QApplication.UnicodeUTF8))
        self.lblImage.setText(QtGui.QApplication.translate("MainWindow", "Image resized to 150 x 150 pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCaseInfo.setText(QtGui.QApplication.translate("MainWindow", "Case Information", None, QtGui.QApplication.UnicodeUTF8))
        self.tbBrowsePath.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.tbDrives.setText(QtGui.QApplication.translate("MainWindow", "Drives", None, QtGui.QApplication.UnicodeUTF8))
        self.tbFilesFolders.setText(QtGui.QApplication.translate("MainWindow", "Files && Folders", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMobile.setText(QtGui.QApplication.translate("MainWindow", "iOS", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAndroid.setText(QtGui.QApplication.translate("MainWindow", "Android", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLoadEvidence.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKeywords.setText(QtGui.QApplication.translate("MainWindow", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKey.setText(QtGui.QApplication.translate("MainWindow", "Keywords that include in your search are specified in number of hits in the results. \n"
"You can import a list of keywords or enter them manualy in the Keywords table below.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLists.setText(QtGui.QApplication.translate("MainWindow", "Lists", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddList.setText(QtGui.QApplication.translate("MainWindow", "add lists", None, QtGui.QApplication.UnicodeUTF8))
        self.lblListsAdded.setText(QtGui.QApplication.translate("MainWindow", "Lists added: 0", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKeywords_2.setText(QtGui.QApplication.translate("MainWindow", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddKeyword.setText(QtGui.QApplication.translate("MainWindow", "add keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKeywordsAdded.setText(QtGui.QApplication.translate("MainWindow", "Keywords added: 0", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddKeywordsToSearch.setText(QtGui.QApplication.translate("MainWindow", "Add keywords to search", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddKeywordsToSearch_2.setText(QtGui.QApplication.translate("MainWindow", "Provide the keywords that you want to include in your search. If a keyword gets a hit during the search,\n"
"it\'s added by number of hits to the results", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddKeywordToSearch.setText(QtGui.QApplication.translate("MainWindow", "add keywords to search", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddHashFilesToSearch.setText(QtGui.QApplication.translate("MainWindow", "Add Hash files to search", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddHashFilesToSearch_txt.setText(QtGui.QApplication.translate("MainWindow", "Import hashes for known media files and Project VIC files so that DigiBaseReclass catagorizes them \n"
"automatically", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddHashFilesToSearch.setText(QtGui.QApplication.translate("MainWindow", "Add Hash files to search", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIgnoreFolders.setText(QtGui.QApplication.translate("MainWindow", "Ignore folder(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIgnoreFolders_txt.setText(QtGui.QApplication.translate("MainWindow", "Provide folder(s) to exclude in the search", None, QtGui.QApplication.UnicodeUTF8))
        self.tbIgnoreFolders_2.setText(QtGui.QApplication.translate("MainWindow", "ignore folder(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOS_Artifacts.setText(QtGui.QApplication.translate("MainWindow", "Add more artifacts", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOS_Artifacts_txt.setText(QtGui.QApplication.translate("MainWindow", "Provide Operating System Artifacts ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbOS_Artifacts.setText(QtGui.QApplication.translate("MainWindow", "add operating system artifacts", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLoadHashFiles.setText(QtGui.QApplication.translate("MainWindow", "load hash files", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLoadHashFiles_txt.setText(QtGui.QApplication.translate("MainWindow", "Import MD5 of CRC hashes for picturres so that DigiBaseReclass Examine categorizes them automatically. \n"
"Each MD5 of CRC value must appear on its own line", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLoadHashFiles.setText(QtGui.QApplication.translate("MainWindow", "add file", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLoadHashFiles_rec_loaded.setText(QtGui.QApplication.translate("MainWindow", "Records loaded: 0", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLoadProjectVic.setText(QtGui.QApplication.translate("MainWindow", "load project vic files", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLoadProjectVic_txt.setText(QtGui.QApplication.translate("MainWindow", "Import Project Vic files so that DigiBaseReclass Examine categorizes the images referencd in the file.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLoadProjectVic_photodna_txt.setText(QtGui.QApplication.translate("MainWindow", "PhotoDNA is currently disabled.", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLoadProjectVic_edit.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLoadProjectVic.setText(QtGui.QApplication.translate("MainWindow", "add project vic file", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLoadProjectVic_rec_loaded.setText(QtGui.QApplication.translate("MainWindow", "Records loaded: 0", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIgnoreFolders_2.setText(QtGui.QApplication.translate("MainWindow", "ignore folder(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIgnoreFolders_txt_2.setText(QtGui.QApplication.translate("MainWindow", "Add those folders that DigiBaseReclass Process need to exclude in the search. ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbIgnoreFoldersAdd.setText(QtGui.QApplication.translate("MainWindow", "add folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tbIgnoreFoldersDel.setText(QtGui.QApplication.translate("MainWindow", "delete folder", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIgnoreFolders_Records.setText(QtGui.QApplication.translate("MainWindow", "Records loaded: 0", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSourcesToProcess.setText(QtGui.QApplication.translate("MainWindow", "Sources to process", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAcquireEvidence.setText(QtGui.QApplication.translate("MainWindow", "ACQUIRE EVIDENCE", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLoadEvidence.setText(QtGui.QApplication.translate("MainWindow", "LOAD EVIDENCE", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_DigiBaseReclass_Examine.setText(QtGui.QApplication.translate("MainWindow", "Open DigiBaseReclass Examine", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("MainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

