# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferencewindow.ui'
#
# Created: Thu Feb 18 08:29:13 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(582, 559)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MainWindow/Tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(False)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 541, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tabAlgemeen = QtGui.QWidget()
        self.tabAlgemeen.setObjectName("tabAlgemeen")
        self.groupBox_11 = QtGui.QGroupBox(self.tabAlgemeen)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 30, 511, 261))
        self.groupBox_11.setObjectName("groupBox_11")
        self.btnAddOpslaglokatieZaken = QtGui.QPushButton(self.groupBox_11)
        self.btnAddOpslaglokatieZaken.setGeometry(QtCore.QRect(460, 29, 41, 23))
        self.btnAddOpslaglokatieZaken.setObjectName("btnAddOpslaglokatieZaken")
        self.leOpslaglokatieZaken = QtGui.QLineEdit(self.groupBox_11)
        self.leOpslaglokatieZaken.setGeometry(QtCore.QRect(80, 30, 361, 20))
        self.leOpslaglokatieZaken.setObjectName("leOpslaglokatieZaken")
        self.label = QtGui.QLabel(self.groupBox_11)
        self.label.setGeometry(QtCore.QRect(10, 30, 46, 13))
        self.label.setObjectName("label")
        self.leOpslaglokatieCRC = QtGui.QLineEdit(self.groupBox_11)
        self.leOpslaglokatieCRC.setGeometry(QtCore.QRect(80, 61, 361, 20))
        self.leOpslaglokatieCRC.setObjectName("leOpslaglokatieCRC")
        self.label_2 = QtGui.QLabel(self.groupBox_11)
        self.label_2.setGeometry(QtCore.QRect(10, 61, 71, 16))
        self.label_2.setObjectName("label_2")
        self.btnAddOpslaglokatieCRC = QtGui.QPushButton(self.groupBox_11)
        self.btnAddOpslaglokatieCRC.setEnabled(False)
        self.btnAddOpslaglokatieCRC.setGeometry(QtCore.QRect(460, 60, 41, 23))
        self.btnAddOpslaglokatieCRC.setObjectName("btnAddOpslaglokatieCRC")
        self.leOpslaglokatieMD5 = QtGui.QLineEdit(self.groupBox_11)
        self.leOpslaglokatieMD5.setGeometry(QtCore.QRect(80, 94, 361, 20))
        self.leOpslaglokatieMD5.setObjectName("leOpslaglokatieMD5")
        self.label_3 = QtGui.QLabel(self.groupBox_11)
        self.label_3.setGeometry(QtCore.QRect(10, 94, 81, 16))
        self.label_3.setObjectName("label_3")
        self.btnAddOpslaglokatieMD5 = QtGui.QPushButton(self.groupBox_11)
        self.btnAddOpslaglokatieMD5.setEnabled(False)
        self.btnAddOpslaglokatieMD5.setGeometry(QtCore.QRect(460, 93, 41, 23))
        self.btnAddOpslaglokatieMD5.setObjectName("btnAddOpslaglokatieMD5")
        self.leOpslaglokatieKeywords = QtGui.QLineEdit(self.groupBox_11)
        self.leOpslaglokatieKeywords.setGeometry(QtCore.QRect(80, 127, 361, 20))
        self.leOpslaglokatieKeywords.setObjectName("leOpslaglokatieKeywords")
        self.label_4 = QtGui.QLabel(self.groupBox_11)
        self.label_4.setGeometry(QtCore.QRect(10, 127, 46, 13))
        self.label_4.setObjectName("label_4")
        self.btnAddOpslaglokatieKeywords = QtGui.QPushButton(self.groupBox_11)
        self.btnAddOpslaglokatieKeywords.setEnabled(False)
        self.btnAddOpslaglokatieKeywords.setGeometry(QtCore.QRect(460, 126, 41, 23))
        self.btnAddOpslaglokatieKeywords.setObjectName("btnAddOpslaglokatieKeywords")
        self.leOpslaglokatieIncludes = QtGui.QLineEdit(self.groupBox_11)
        self.leOpslaglokatieIncludes.setGeometry(QtCore.QRect(80, 159, 361, 20))
        self.leOpslaglokatieIncludes.setObjectName("leOpslaglokatieIncludes")
        self.label_5 = QtGui.QLabel(self.groupBox_11)
        self.label_5.setGeometry(QtCore.QRect(10, 159, 46, 13))
        self.label_5.setObjectName("label_5")
        self.btnAddOpslaglokatieIncludes = QtGui.QPushButton(self.groupBox_11)
        self.btnAddOpslaglokatieIncludes.setEnabled(False)
        self.btnAddOpslaglokatieIncludes.setGeometry(QtCore.QRect(460, 158, 41, 23))
        self.btnAddOpslaglokatieIncludes.setObjectName("btnAddOpslaglokatieIncludes")
        self.btnAddOpslaglokatieExcludes = QtGui.QPushButton(self.groupBox_11)
        self.btnAddOpslaglokatieExcludes.setEnabled(False)
        self.btnAddOpslaglokatieExcludes.setGeometry(QtCore.QRect(460, 191, 41, 23))
        self.btnAddOpslaglokatieExcludes.setObjectName("btnAddOpslaglokatieExcludes")
        self.label_6 = QtGui.QLabel(self.groupBox_11)
        self.label_6.setGeometry(QtCore.QRect(10, 192, 46, 13))
        self.label_6.setObjectName("label_6")
        self.leOpslaglokatieExludes = QtGui.QLineEdit(self.groupBox_11)
        self.leOpslaglokatieExludes.setGeometry(QtCore.QRect(80, 190, 361, 20))
        self.leOpslaglokatieExludes.setText("")
        self.leOpslaglokatieExludes.setObjectName("leOpslaglokatieExludes")
        self.tabWidget.addTab(self.tabAlgemeen, "")
        self.tabCRC = QtGui.QWidget()
        self.tabCRC.setObjectName("tabCRC")
        self.groupBox = QtGui.QGroupBox(self.tabCRC)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 421, 91))
        self.groupBox.setObjectName("groupBox")
        self.btnAddSingleCrcHash = QtGui.QPushButton(self.groupBox)
        self.btnAddSingleCrcHash.setGeometry(QtCore.QRect(319, 29, 75, 23))
        self.btnAddSingleCrcHash.setObjectName("btnAddSingleCrcHash")
        self.leSingleCRC = QtGui.QLineEdit(self.groupBox)
        self.leSingleCRC.setGeometry(QtCore.QRect(22, 30, 271, 20))
        self.leSingleCRC.setObjectName("leSingleCRC")
        self.groupBox_2 = QtGui.QGroupBox(self.tabCRC)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 160, 421, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.listViewCRC = QtGui.QListView(self.groupBox_2)
        self.listViewCRC.setGeometry(QtCore.QRect(23, 100, 371, 201))
        self.listViewCRC.setObjectName("listViewCRC")
        self.btnFileFolderCrc = QtGui.QPushButton(self.groupBox_2)
        self.btnFileFolderCrc.setGeometry(QtCore.QRect(319, 29, 75, 23))
        self.btnFileFolderCrc.setObjectName("btnFileFolderCrc")
        self.leMultipleCRC = QtGui.QLineEdit(self.groupBox_2)
        self.leMultipleCRC.setGeometry(QtCore.QRect(22, 30, 271, 20))
        self.leMultipleCRC.setObjectName("leMultipleCRC")
        self.btnAddCrcMultipleHash = QtGui.QPushButton(self.groupBox_2)
        self.btnAddCrcMultipleHash.setGeometry(QtCore.QRect(319, 60, 75, 23))
        self.btnAddCrcMultipleHash.setObjectName("btnAddCrcMultipleHash")
        self.tabWidget.addTab(self.tabCRC, "")
        self.tabMD5 = QtGui.QWidget()
        self.tabMD5.setObjectName("tabMD5")
        self.groupBox_5 = QtGui.QGroupBox(self.tabMD5)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 40, 421, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.btnAddSingleMD5Hash = QtGui.QPushButton(self.groupBox_5)
        self.btnAddSingleMD5Hash.setGeometry(QtCore.QRect(319, 29, 75, 23))
        self.btnAddSingleMD5Hash.setObjectName("btnAddSingleMD5Hash")
        self.leSingleMD5 = QtGui.QLineEdit(self.groupBox_5)
        self.leSingleMD5.setGeometry(QtCore.QRect(22, 30, 271, 20))
        self.leSingleMD5.setObjectName("leSingleMD5")
        self.groupBox_6 = QtGui.QGroupBox(self.tabMD5)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 160, 421, 321))
        self.groupBox_6.setObjectName("groupBox_6")
        self.listViewMD5 = QtGui.QListView(self.groupBox_6)
        self.listViewMD5.setGeometry(QtCore.QRect(23, 100, 371, 201))
        self.listViewMD5.setObjectName("listViewMD5")
        self.btnFileFolderMD5 = QtGui.QPushButton(self.groupBox_6)
        self.btnFileFolderMD5.setGeometry(QtCore.QRect(319, 30, 75, 23))
        self.btnFileFolderMD5.setObjectName("btnFileFolderMD5")
        self.leMultipleMD5 = QtGui.QLineEdit(self.groupBox_6)
        self.leMultipleMD5.setGeometry(QtCore.QRect(22, 30, 271, 20))
        self.leMultipleMD5.setObjectName("leMultipleMD5")
        self.btnAddMD5MultipleHash = QtGui.QPushButton(self.groupBox_6)
        self.btnAddMD5MultipleHash.setGeometry(QtCore.QRect(319, 60, 75, 23))
        self.btnAddMD5MultipleHash.setObjectName("btnAddMD5MultipleHash")
        self.tabWidget.addTab(self.tabMD5, "")
        self.tabKeywords = QtGui.QWidget()
        self.tabKeywords.setObjectName("tabKeywords")
        self.groupBox_3 = QtGui.QGroupBox(self.tabKeywords)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 40, 421, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnAddSingleKeyword = QtGui.QPushButton(self.groupBox_3)
        self.btnAddSingleKeyword.setGeometry(QtCore.QRect(319, 29, 75, 23))
        self.btnAddSingleKeyword.setObjectName("btnAddSingleKeyword")
        self.leSingleKeyword = QtGui.QLineEdit(self.groupBox_3)
        self.leSingleKeyword.setGeometry(QtCore.QRect(22, 30, 271, 20))
        self.leSingleKeyword.setObjectName("leSingleKeyword")
        self.groupBox_4 = QtGui.QGroupBox(self.tabKeywords)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 160, 421, 321))
        self.groupBox_4.setObjectName("groupBox_4")
        self.listViewKeywords = QtGui.QListView(self.groupBox_4)
        self.listViewKeywords.setGeometry(QtCore.QRect(23, 100, 371, 201))
        self.listViewKeywords.setObjectName("listViewKeywords")
        self.btnFileFolderKeyword = QtGui.QPushButton(self.groupBox_4)
        self.btnFileFolderKeyword.setGeometry(QtCore.QRect(319, 29, 75, 23))
        self.btnFileFolderKeyword.setObjectName("btnFileFolderKeyword")
        self.leMultipleKeywords = QtGui.QLineEdit(self.groupBox_4)
        self.leMultipleKeywords.setGeometry(QtCore.QRect(22, 30, 271, 20))
        self.leMultipleKeywords.setObjectName("leMultipleKeywords")
        self.btnAddKeywordsMultiple = QtGui.QPushButton(self.groupBox_4)
        self.btnAddKeywordsMultiple.setGeometry(QtCore.QRect(319, 60, 75, 23))
        self.btnAddKeywordsMultiple.setObjectName("btnAddKeywordsMultiple")
        self.tabWidget.addTab(self.tabKeywords, "")
        self.tabIncludes = QtGui.QWidget()
        self.tabIncludes.setObjectName("tabIncludes")
        self.groupBox_7 = QtGui.QGroupBox(self.tabIncludes)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 40, 421, 91))
        self.groupBox_7.setObjectName("groupBox_7")
        self.btnAddSingleFileExtension = QtGui.QPushButton(self.groupBox_7)
        self.btnAddSingleFileExtension.setGeometry(QtCore.QRect(319, 29, 75, 23))
        self.btnAddSingleFileExtension.setObjectName("btnAddSingleFileExtension")
        self.leSingleFileExtension = QtGui.QLineEdit(self.groupBox_7)
        self.leSingleFileExtension.setGeometry(QtCore.QRect(22, 30, 271, 20))
        self.leSingleFileExtension.setObjectName("leSingleFileExtension")
        self.groupBox_8 = QtGui.QGroupBox(self.tabIncludes)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 160, 421, 321))
        self.groupBox_8.setObjectName("groupBox_8")
        self.listViewFileExtensions = QtGui.QListView(self.groupBox_8)
        self.listViewFileExtensions.setGeometry(QtCore.QRect(23, 100, 371, 201))
        self.listViewFileExtensions.setObjectName("listViewFileExtensions")
        self.btnFileFolderFileExtensions = QtGui.QPushButton(self.groupBox_8)
        self.btnFileFolderFileExtensions.setGeometry(QtCore.QRect(319, 29, 75, 23))
        self.btnFileFolderFileExtensions.setObjectName("btnFileFolderFileExtensions")
        self.leMultipleFileExtensions = QtGui.QLineEdit(self.groupBox_8)
        self.leMultipleFileExtensions.setGeometry(QtCore.QRect(22, 30, 271, 20))
        self.leMultipleFileExtensions.setObjectName("leMultipleFileExtensions")
        self.btnAddFileExtensionsMultiple = QtGui.QPushButton(self.groupBox_8)
        self.btnAddFileExtensionsMultiple.setGeometry(QtCore.QRect(319, 60, 75, 23))
        self.btnAddFileExtensionsMultiple.setObjectName("btnAddFileExtensionsMultiple")
        self.tabWidget.addTab(self.tabIncludes, "")
        self.tabExcludes = QtGui.QWidget()
        self.tabExcludes.setObjectName("tabExcludes")
        self.groupBox_9 = QtGui.QGroupBox(self.tabExcludes)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 40, 421, 91))
        self.groupBox_9.setObjectName("groupBox_9")
        self.btnAddSingleFolder = QtGui.QPushButton(self.groupBox_9)
        self.btnAddSingleFolder.setGeometry(QtCore.QRect(319, 29, 75, 23))
        self.btnAddSingleFolder.setObjectName("btnAddSingleFolder")
        self.leSingleFolder = QtGui.QLineEdit(self.groupBox_9)
        self.leSingleFolder.setGeometry(QtCore.QRect(22, 30, 271, 20))
        self.leSingleFolder.setObjectName("leSingleFolder")
        self.groupBox_10 = QtGui.QGroupBox(self.tabExcludes)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 160, 421, 321))
        self.groupBox_10.setObjectName("groupBox_10")
        self.listViewExcludeFolders = QtGui.QListView(self.groupBox_10)
        self.listViewExcludeFolders.setGeometry(QtCore.QRect(23, 100, 371, 201))
        self.listViewExcludeFolders.setObjectName("listViewExcludeFolders")
        self.btnFileFolderExcludeFolders = QtGui.QPushButton(self.groupBox_10)
        self.btnFileFolderExcludeFolders.setGeometry(QtCore.QRect(319, 29, 75, 23))
        self.btnFileFolderExcludeFolders.setObjectName("btnFileFolderExcludeFolders")
        self.leMultipleFolders = QtGui.QLineEdit(self.groupBox_10)
        self.leMultipleFolders.setGeometry(QtCore.QRect(22, 30, 271, 20))
        self.leMultipleFolders.setObjectName("leMultipleFolders")
        self.btnAddExcludeMultipleFolders = QtGui.QPushButton(self.groupBox_10)
        self.btnAddExcludeMultipleFolders.setGeometry(QtCore.QRect(319, 60, 75, 23))
        self.btnAddExcludeMultipleFolders.setObjectName("btnAddExcludeMultipleFolders")
        self.tabWidget.addTab(self.tabExcludes, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("Dialog", "Lokaties", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddOpslaglokatieZaken.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Zaken", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "CRC hashes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddOpslaglokatieCRC.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "MD5 hashes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddOpslaglokatieMD5.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddOpslaglokatieKeywords.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Includes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddOpslaglokatieIncludes.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddOpslaglokatieExcludes.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Excludes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAlgemeen), QtGui.QApplication.translate("Dialog", "Algemeen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Enkele CRC hashwaarde toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSingleCrcHash.setText(QtGui.QApplication.translate("Dialog", "Toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Meerdere CRC hashwaarden uit txtbestand toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFileFolderCrc.setText(QtGui.QApplication.translate("Dialog", "....", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddCrcMultipleHash.setText(QtGui.QApplication.translate("Dialog", "Toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCRC), QtGui.QApplication.translate("Dialog", "CRC Hashes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Enkele MD5 hashwaarde toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSingleMD5Hash.setText(QtGui.QApplication.translate("Dialog", "Toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog", "Meerdere MD5 hashwaarden uit txtbestand toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFileFolderMD5.setText(QtGui.QApplication.translate("Dialog", "....", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddMD5MultipleHash.setText(QtGui.QApplication.translate("Dialog", "Toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMD5), QtGui.QApplication.translate("Dialog", "MD5 hashes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Enkel Keyword toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSingleKeyword.setText(QtGui.QApplication.translate("Dialog", "Toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Meerdere Keywords uit txtbestand toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFileFolderKeyword.setText(QtGui.QApplication.translate("Dialog", "....", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddKeywordsMultiple.setText(QtGui.QApplication.translate("Dialog", "Toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabKeywords), QtGui.QApplication.translate("Dialog", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Dialog", "Enkele bestandsextensie toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSingleFileExtension.setText(QtGui.QApplication.translate("Dialog", "Toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.leSingleFileExtension.setPlaceholderText(QtGui.QApplication.translate("Dialog", "like *.jpg", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Dialog", "Meerdere bestandsextensies uit txtbestand toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFileFolderFileExtensions.setText(QtGui.QApplication.translate("Dialog", "....", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddFileExtensionsMultiple.setText(QtGui.QApplication.translate("Dialog", "Toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIncludes), QtGui.QApplication.translate("Dialog", "Include file_extensions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Dialog", "Enkele map toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSingleFolder.setText(QtGui.QApplication.translate("Dialog", "Toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("Dialog", "Meerdere mappen uit txtbestand toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFileFolderExcludeFolders.setText(QtGui.QApplication.translate("Dialog", "....", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddExcludeMultipleFolders.setText(QtGui.QApplication.translate("Dialog", "Toevoegen", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExcludes), QtGui.QApplication.translate("Dialog", "Exclude folders", None, QtGui.QApplication.UnicodeUTF8))

#import bron.resources
